# Generated by Django 2.2 on 2020-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=200)),
                ('order_due_date', models.CharField(max_length=200)),
                ('order_deliver_data', models.CharField(max_length=200)),
                ('order_address', models.CharField(max_length=200)),
                ('order_item_name', models.CharField(max_length=200)),
                ('order_item_quantity', models.CharField(max_length=200)),
            ],
        ),
    ]
