# Generated by Django 2.2 on 2020-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
