# Generated by Django 2.2 on 2020-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0004_auto_20200920_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=100, unique=True)),
                ('vendor_phone', models.IntegerField(default=880, max_length=100, unique=True)),
                ('vend_address', models.CharField(max_length=200)),
            ],
        ),
    ]
