# Generated by Django 2.2 on 2020-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0005_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_phone',
            field=models.IntegerField(default=880, unique=True),
        ),
    ]
