# Generated by Django 2.2 on 2020-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0006_auto_20200920_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_phone',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
