# Generated by Django 2.2 on 2020-09-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0007_auto_20200920_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vend_address',
            new_name='vendor_address',
        ),
    ]
