# Generated by Django 2.2 on 2020-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurebd_api', '0008_auto_20200920_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_item_catagory',
            field=models.CharField(default='Catagory1', max_length=100),
        ),
    ]
